version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  run_tests:
    docker:
      - image: circleci/ruby:2.6.4-node
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install