version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4-node
    steps:
      - checkout
      - run:
          name: 'install dep'
          command: apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: npm install
          command: npm install
      - run:
          name: run test
          command: $(npm bin)/cypress run