version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4-node
      - image: benweizhu/my-node-image
          volumes:
            - ./index.js:/usr/app/index.js
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install